In [1]:
%matplotlib inline

from time import time

from math import sqrt, floor
import numpy as np

import matplotlib.pyplot as plt
plt.style.use = "default"

import pandas as pd
pd.options.display.float_format = '{:.3f}'.format

from IPython.core.debugger import set_trace

import sys
sys.path.append('../../')
from rfc import RandomForest
from Experiment import Experiment

In [2]:
train = pd.read_csv("cleaned_train.csv")
labels = pd.read_csv("cleaned_label.csv")

In [3]:
train = train.drop(train.columns[0], axis=1)
labels = labels.drop(labels.columns[0], axis=1) 
labels = labels.rename(columns={"9": "label"})

In [4]:
train.describe()

,0,1,2,3,4,5,6,7,8,9,10,11,12
count,2693.000,2693.000,2693.000,2693.000,2693.000,2693.000,2693.000,2693.000,2693.000,2693.000,2693.000,2693.000,2693.000
mean,1.541,24136653.576,3.407,12253995.652,15967326.421,77979951.886,1.496,44931306.014,0.618,23393986.221,36019311.156,5570002.221,59784627.869
std,0.498,153501863.784,1.635,110037846.416,125372261.145,268189827.436,0.712,207191751.434,1.009,151179339.534,186372789.674,74438087.894,237131410.035
min,1.000,1.000,1.000,1.000,1.000,1.000,1.000,1.000,0.000,1.000,1.000,1.000,1.000
25%,1.000,1.000,2.000,3.000,1.000,4.000,1.000,2.000,0.000,1.000,1.000,5.000,1.000
50%,2.000,3.000,3.000,4.000,4.000,5.000,1.000,3.000,0.000,2.000,1.000,7.000,1.000
75%,2.000,5.000,4.000,5.000,6.000,5.000,2.000,4.000,1.000,2.000,3.000,7.000,1.000
max,2.000,1000000000.000,7.000,1000000000.000,1000000000.000,1000000000.000,3.000,1000000000.000,7.000,1000000000.000,1000000000.000,1000000000.000,1000000000.000

In [5]:
def merge(df, labels):
    return labels.merge(df, left_index=True,right_index=True)

In [6]:
def mprint(*args):
    for arg in args:
        print(arg)
        print(" ")

In [7]:
merge(train, labels).groupby("label").describe()

            0                                                 1               \
        count  mean   std   min   25%   50%   75%   max   count         mean
label
1     547.000 1.565 0.496 1.000 1.000 2.000 2.000 2.000 547.000 32906767.112
2     256.000 1.570 0.496 1.000 1.000 2.000 2.000 2.000 256.000 15625003.133
3     215.000 1.553 0.498 1.000 1.000 2.000 2.000 2.000 215.000 23255816.995
4     247.000 1.534 0.500 1.000 1.000 2.000 2.000 2.000 247.000 28340083.919
5     213.000 1.568 0.497 1.000 1.000 2.000 2.000 2.000 213.000  9389674.592
6     315.000 1.492 0.501 1.000 1.000 1.000 2.000 2.000 315.000 31746034.698
7     279.000 1.530 0.500 1.000 1.000 2.000 2.000 2.000 279.000 32258067.527
8     383.000 1.517 0.500 1.000 1.000 2.000 2.000 2.000 383.000 20887731.465
9     238.000 1.538 0.500 1.000 1.000 2.000 2.000 2.000 238.000  8403364.189

           ...           8             9                                   \
           ...         75%   max   count         mean           std   min
label      ...
1          ...       1.000 7.000 547.000 25594151.707 158065699.298 1.000
2          ...       1.000 5.000 256.000 15625001.781 124262530.212 1.000
3          ...       1.000 4.000 215.000 37209304.140 189716039.065 1.000
4          ...       1.000 4.000 247.000 16194333.802 126478615.075 1.000
5          ...       1.000 5.000 213.000 32863851.671 178700141.812 1.000
6          ...       1.000 6.000 315.000 28571430.400 166863698.810 1.000
7          ...       1.000 6.000 279.000 14336919.423 119089053.113 1.000
8          ...       1.000 6.000 383.000 23498696.332 151679185.041 1.000
9          ...       1.000 4.000 238.000 16806724.441 128817620.319 1.000


        25%   50%   75%            max
label
1     1.000 2.000 2.000 1000000000.000
2     1.000 2.000 2.000 1000000000.000
3     1.000 2.000 2.000 1000000000.000
4     1.000 2.000 2.000 1000000000.000
5     1.000 2.000 3.000 1000000000.000
6     1.000 2.000 2.000 1000000000.000
7     1.000 2.000 2.000 1000000000.000
8     1.000 2.000 2.000 1000000000.000
9     1.000 2.000 2.000 1000000000.000

[9 rows x 104 columns]

In [8]:
init_config_names = ["num_trees", "num_features", "num_sample_rows", "max_tree_depth", "min_split_samples", "bias_class", "bias_amount"]
init_config_values = [   10,          4,           20,              20,                5,                 None,            0]

e = Experiment(train, labels, RandomForest, init_config_names, init_config_values, verbose=True)

In [9]:
t1 = e.run_trial()

Running trail #1
------------------------------------

*************************

Running fold 1 of 10

*************************


*** Creating tree #1 ***


parsing @ depth 1


classified 6 at depth 1 to be in class 8


*** Creating tree #2 ***


parsing @ depth 1


classified 9 at depth 1 to be in class 1


*** Creating tree #3 ***


parsing @ depth 1


parsing @ depth 2

KeyError: -1

In [10]:
perf, train_test = e.trial_results()

In [11]:
perf

,num_trees,num_features,num_sample_rows,max_tree_depth,min_split_samples,bias_class,bias_amount,log_loss,class_accuracy,precision,recall,f1-score,support,trial_num
0,10.000,4.000,20.000,20.000,5.000,-1.000,0.000,2.197,0.217,0.047,0.217,0.078,nan,1.000
1,10.000,4.000,20.000,20.000,5.000,-1.000,0.000,2.197,0.176,0.031,0.176,0.053,nan,1.000
2,10.000,4.000,20.000,20.000,5.000,-1.000,0.000,2.197,0.187,0.035,0.187,0.059,nan,1.000
3,10.000,4.000,20.000,20.000,5.000,-1.000,0.000,2.197,0.187,0.035,0.187,0.059,nan,1.000
4,10.000,4.000,20.000,20.000,5.000,-1.000,0.000,2.197,0.213,0.045,0.213,0.075,nan,1.000
5,10.000,4.000,20.000,20.000,5.000,-1.000,0.000,2.197,0.181,0.033,0.181,0.055,nan,1.000
6,10.000,4.000,20.000,20.000,5.000,-1.000,0.000,2.197,0.127,0.016,0.127,0.029,nan,1.000
7,10.000,4.000,20.000,20.000,5.000,-1.000,0.000,2.197,0.198,0.039,0.198,0.066,nan,1.000
8,10.000,4.000,20.000,20.000,5.000,-1.000,0.000,2.197,0.219,0.048,0.219,0.079,nan,1.000
9,10.000,4.000,20.000,20.000,5.000,-1.000,0.000,2.197,0.189,0.036,0.189,0.060,nan,1.000

# Trial 1 Notes
I think the number of rows had something to do with it.

In [12]:
e.tweak("num_sample_rows", 40).tweak("num_features", train.columns.size).tweak("min_split_samples", 2).tweak("num_trees", 20)

In [13]:
t2 = e.run_trial()

Running trail #11
------------------------------------

*************************

Running fold 1 of 10

*************************


*** Creating tree #1 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 7


*** Creating tree #2 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #3 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 3


*** Creating tree #4 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 6


*** Creating tree #5 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 3


*** Creating tree #6 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 8


*** Creating tree #7 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #8 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 8


*** Creating tree #9 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #10 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #11 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #12 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 8


*** Creating tree #13 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 7


*** Creating tree #14 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 5


*** Creating tree #15 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #16 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 5


*** Creating tree #17 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #18 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #19 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #20 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1

fold 1 took 174.69338202476501s

*************************

Running fold 2 of 10

*************************


*** Creating tree #1 ***


parsing @ depth 1

/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/sklearn/metrics/classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #2 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 8


*** Creating tree #3 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #4 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #5 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #6 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #7 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #8 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 6


*** Creating tree #9 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #10 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 8


*** Creating tree #11 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 5


*** Creating tree #12 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 8


*** Creating tree #13 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #14 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 4


*** Creating tree #15 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #16 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #17 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #18 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #19 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #20 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 6

fold 2 took 198.34293913841248s

*************************

Running fold 3 of 10

*************************


*** Creating tree #1 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 8


*** Creating tree #2 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #3 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #4 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 8


*** Creating tree #5 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #6 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 9


*** Creating tree #7 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #8 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #9 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #10 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 6


*** Creating tree #11 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #12 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #13 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #14 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #15 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #16 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #17 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #18 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #19 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 2


*** Creating tree #20 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 6

fold 3 took 196.00404500961304s

*************************

Running fold 4 of 10

*************************


*** Creating tree #1 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #2 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 4


*** Creating tree #3 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 9


*** Creating tree #4 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 6


*** Creating tree #5 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 6


*** Creating tree #6 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 8


*** Creating tree #7 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #8 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #9 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #10 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 6


*** Creating tree #11 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #12 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #13 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #14 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 7


*** Creating tree #15 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 2


*** Creating tree #16 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 8


*** Creating tree #17 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #18 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #19 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #20 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 8

fold 4 took 183.61101412773132s

*************************

Running fold 5 of 10

*************************


*** Creating tree #1 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 6


*** Creating tree #2 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #3 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #4 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #5 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #6 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 8


*** Creating tree #7 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #8 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #9 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #10 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #11 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #12 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #13 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #14 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 3


*** Creating tree #15 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #16 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 3


*** Creating tree #17 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #18 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 6


*** Creating tree #19 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 3


*** Creating tree #20 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1

fold 5 took 160.0157859325409s

*************************

Running fold 6 of 10

*************************


*** Creating tree #1 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #2 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #3 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #4 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #5 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #6 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #7 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #8 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #9 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #10 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #11 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #12 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 7


*** Creating tree #13 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #14 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #15 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 7


*** Creating tree #16 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #17 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #18 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #19 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #20 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 7

fold 6 took 146.36124801635742s

*************************

Running fold 7 of 10

*************************


*** Creating tree #1 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 6


*** Creating tree #2 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 4


*** Creating tree #3 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #4 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 8


*** Creating tree #5 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 7


*** Creating tree #6 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #7 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #8 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #9 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 6


*** Creating tree #10 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 3


*** Creating tree #11 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #12 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 8


*** Creating tree #13 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #14 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 8


*** Creating tree #15 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #16 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #17 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #18 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 3


*** Creating tree #19 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #20 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1

fold 7 took 151.73499488830566s

*************************

Running fold 8 of 10

*************************


*** Creating tree #1 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #2 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 6


*** Creating tree #3 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 3


*** Creating tree #4 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 6


*** Creating tree #5 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #6 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #7 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #8 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #9 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 8


*** Creating tree #10 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #11 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #12 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 7


*** Creating tree #13 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #14 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 6


*** Creating tree #15 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 8


*** Creating tree #16 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #17 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #18 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #19 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #20 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1

fold 8 took 148.6282889842987s

*************************

Running fold 9 of 10

*************************


*** Creating tree #1 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 8


*** Creating tree #2 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #3 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #4 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 3


*** Creating tree #5 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 2


*** Creating tree #6 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 8


*** Creating tree #7 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #8 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #9 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #10 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #11 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 8


*** Creating tree #12 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #13 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #14 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 2


*** Creating tree #15 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 6


*** Creating tree #16 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 7


*** Creating tree #17 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 8


*** Creating tree #18 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 2


*** Creating tree #19 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 7


*** Creating tree #20 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 8

fold 9 took 147.36570382118225s

*************************

Running fold 10 of 10

*************************


*** Creating tree #1 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #2 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #3 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 8


*** Creating tree #4 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #5 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #6 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #7 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #8 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 6


*** Creating tree #9 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 5


*** Creating tree #10 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #11 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 6


*** Creating tree #12 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #13 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #14 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1


*** Creating tree #15 ***


parsing @ depth 1


classified 1.00000000000000e+99 at depth 1 to be in class 1



In [14]:
t2[0]

,num_trees,num_features,num_sample_rows,max_tree_depth,min_split_samples,bias_class,bias_amount,log_loss,class_accuracy,precision,recall,f1-score,support,trial_num
10,20.000,13.000,40.000,20.000,2.000,-1.000,0.000,2.197,0.225,0.051,0.225,0.083,nan,2.000
11,20.000,13.000,40.000,20.000,2.000,-1.000,0.000,2.197,0.192,0.037,0.192,0.062,nan,2.000
12,20.000,13.000,40.000,20.000,2.000,-1.000,0.000,2.197,0.186,0.034,0.186,0.058,nan,2.000
13,20.000,13.000,40.000,20.000,2.000,-1.000,0.000,2.197,0.202,0.041,0.202,0.068,nan,2.000
14,20.000,13.000,40.000,20.000,2.000,-1.000,0.000,2.197,0.195,0.038,0.195,0.064,nan,2.000
15,20.000,13.000,40.000,20.000,2.000,-1.000,0.000,2.197,0.195,0.038,0.195,0.064,nan,2.000
16,20.000,13.000,40.000,20.000,2.000,-1.000,0.000,2.197,0.214,0.046,0.214,0.076,nan,2.000
17,20.000,13.000,40.000,20.000,2.000,-1.000,0.000,2.197,0.184,0.034,0.184,0.057,nan,2.000
18,20.000,13.000,40.000,20.000,2.000,-1.000,0.000,2.197,0.192,0.037,0.192,0.062,nan,2.000
19,20.000,13.000,40.000,20.000,2.000,-1.000,0.000,2.197,0.175,0.031,0.175,0.052,nan,2.000

In [22]:
test = pd.read_csv("cleaned_test.csv")
test = test.drop(columns=test.columns[0])

In [23]:
test

      0  1  2  3  4  5  6  7  8  9  10  11  12
0     1  5  3  4  1  5  1  3  0  1   1   7   1
1     2  1  4  3  5  5  3  2  0  1   1   7   1
2     1  5  2  3  9  2  1  4  0  3   1   7   1
3     1  2  2  2  3  2  1  4  0  3   3   7   1
4     2  5  3  4  1  2  1  1  0  2   2   7   1
5     2  5  1  2  6  5  1  4  0  3   1   3   1
6     1  2  1  2  3  5  1  2  0  3   3   5   2
7     2  1  2  4  5  5  3  2  0  2   3   7   1
8     2  1  4  4  5  5  3  5  0  1   1   7   1
9     1  1  4  6  1  3  2  3  0  1   1   7   1
10    1  5  3  5  2  5  1  3  0  1   2   7   1
11    1  1  4  6  1  5  3  5  0  1   1   5   1
12    2  4  6  3  8  5  1  2  0  2   3   7   1
13    1  3  3  6  2  2  2  1  0  1   1   7   1
14    1  1  7  4  8  3  3  3  0  2   3   7   1
15    2  1  7  2  3  4  3  3  0  2   3   7   1
16    1  1  5  4  2  5  2  2  0  2   1   3   1
17    2  1  5  5  5  4  3  2  0  2   3   7   1
18    2  1  3  3  4  5  2  6  0  1   1   5   1
19    1  3  3  5  1  5  1  3  0  1   1   3   1
20    1  1  5  4  1  5  3  3  0  1   1   2   1
21    1  1  6  5  1  5  2  3  0  1   1   2   1
22    2  1  6  4  4  5  2  2  0  1   1   2   1
23    2  4  6  3  5  5  1  2  0  2   3   7   1
24    2  1  6  3  5  5  2  4  0  1   1   2   3
25    1  2  5  5  1  5  2  3  0  1   1   5   1
26    1  5  1  2  2  5  1  4  0  3   1   8   1
27    1  5  1  1  6  3  1  4  0  3   2   8   1
28    1  5  1  1  6  5  1  6  0  3   1   5   2
29    2  5  1  1  6  5  1  4  0  3   2   7   1
...  .. .. .. .. .. .. .. .. .. ..  ..  ..  ..
2663  2  1  6  5  1  5  2  2  0  1   1   7   1
2664  1  3  3  5  1  5  1  2  0  1   1   7   1
2665  1  3  5  6  1  5  2  4  0  1   1   7   1
2666  1  5  1  2  6  5  1  3  0  3   1   7   1
2667  2  5  1  2  6  5  1  4  0  3   1   5   1
2668  1  5  3  4  4  5  1  2  0  2   3   7   1
2669  2  5  2  4  4  5  1  3  0  2   1   7   1
2670  1  1  7  4  8  5  3  2  0  1   1   7   1
2671  1  4  3  4  1  5  1  3  0  2   1   7   1
2672  2  5  2  3  6  2  1  4  0  3   3   7   1
2673  1  3  3  4  1  2  1  2  0  2   1   5   1
2674  1  5  2  4  4  5  1  1  0  2   2   7   1
2675  2  3  4  4  1  5  1  1  0  1   2   7   1
2676  1  5  3  5  2  5  1  1  0  2   3   7   1
2677  1  5  2  3  3  5  1  1  0  2   1   2   1
2678  1  5  4  6  4  4  1  2  0  1   1   7   1
2679  2  1  4  6  5  5  3  5  0  1   1   5   1
2680  1  5  1  2  6  5  1  2  0  3   1   7   1
2681  2  5  1  2  6  5  1  4  0  3   1   7   1
2682  1  5  2  3  4  5  1  4  0  3   1   7   1
2683  1  5  3  4  6  5  1  2  0  2   5   7   1
2684  1  5  2  4  4  2  1  3  0  2   5   8   3
2685  2  5  2  4  4  2  1  4  0  2   1   7   1
2686  1  5  3  4  6  2  1  3  0  2   3   8   3
2687  1  1  3  6  1  5  2  2  0  1   1   7   1
2688  2  5  1  1  2  5  1  3  0  3   1   7   1
2689  1  5  2  4  1  5  1  4  0  3   1   7   1
2690  2  5  1  2  1  5  1  3  0  3   1   7   1
2691  1  1  6  4  3  5  2  3  0  2   3   7   1
2692  1  5  3  4  1  5  1  1  0  2   3   5   1

[2693 rows x 13 columns]

In [25]:
t = test.apply(lambda x: e.experiment_data[-1][0].predict(x))
t.to_csv("predictions3.txt", sep="\t", index=False, header=False)